baseurl = "https://jduabe.dev"
title = "jduabe.dev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji=true
canonifyurls = true
paginate = 10

[markup]
  [markup.highlight]
    noClasses = true
    style = "base16-snazzy"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
  author = "Jordan Duabe"
  email = "me@jduabe.dev"
  info = "Polyglot developer and open-source enthusiast"
  description = "Personal website and blog"
  keywords = "blog,programmer,personal"
  gravatar = "jordan.duabe@gmail.com"

  favicon_32 = "favicon-32x32.png"
  favicon_16 = "favicon-16x16.png"
  faviconSVG = "favicon.svg"
  touchIcon = "apple-touch-icon.png"

  enableTwemoji = true

  colorScheme = "auto"
  hideColorSchemeToggle = false

  customCSS = ["css/custom.css"]
  customSCSS = ["scss/custom.scss"]
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:me@jduabe.dev"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/j4ckofalltrades"

[[params.social]]
  name = "Mastodon"
  icon = "fa-brands fa-mastodon fa-2x"
  weight = 3
  rel = "me"
  url = "https://fosstodon.org/@j4ckofalltrades"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin-in fa-2x"
  weight = 4
  url = "https://linkedin.com/in/jordan-duabe"

[[params.social]]
  name = "Discord"
  icon = "fa-brands fa-discord fa-2x"
  weight = 5
  rel = "me"
  url = "https://discord.com/users/556870829539852349"

[[params.social]]
  name = "YouTube"
  icon = "fa-brands fa-youtube fa-2x"
  weight = 6
  url = "https://youtube.com/@j4ckofalltrades"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 7
  url = "posts/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[[params.social]]
  name = "Key"
  icon = "fa fa-key fa-2x"
  weight = 8
  url = "key.asc"

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"

[[menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"

[[menu.main]]
  name = "Talks"
  weight = 4
  url  = "talks/"
