baseurl = "https://jduabe.dev"
title = "Jordan Duabe's Weblog"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji=true
canonifyurls = true
pagerSize = 10
pluralizeListTitles = false

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
    excludeFiles = ['templates/**']
  [[module.imports]]
    path = "github.com/luizdepra/hugo-coder"
  [[module.imports]]
    path = "cj.rs/gohugo-asciinema"

[markup]
  [markup.highlight]
    noClasses = true
    style = "github-dark"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = 10

[params]
  author = "Jordan Duabe"
  email = "me@jduabe.dev"
  info = "Software Engineer"
  description = "Personal website and blog"
  keywords = "blog,programmer"
  gravatar = "me@jduabe.dev"
  fediverseCreator = "@j4ckofalltrades@infosec.exchange"

  enableTwemoji = true

  colorScheme = "auto"
  hideColorSchemeToggle = false

  customCSS = []
  customSCSS = ["scss/custom.scss"]
  customJS = []

  [params.mastodon]
    host = "fosstodon.org"
    username = "j4ckofalltrades"
    purifyCDN = "https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:me@jduabe.dev"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  target = "_blank"
  url = "https://github.com/j4ckofalltrades"

[[params.social]]
  name = "Mastodon"
  icon = "fa-brands fa-mastodon fa-2x"
  weight = 3
  target = "_blank"
  rel = "me"
  url = "https://infosec.exchange/@j4ckofalltrades"

[[params.social]]
  name = "ORCID"
  icon = "fa-brands fa-orcid fa-2x"
  weight = 4
  target = "_blank"
  url = "https://orcid.org/0009-0006-4805-0252"

[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 5
  url = "posts/index.xml"
  rel = "alternate"
  target = "_blank"
  type = "application/rss+xml"

[[params.social]]
  name = "Key"
  icon = "fa fa-key fa-2x"
  weight = 8
  target = "_blank"
  url = "https://keys.openpgp.org/search?q=me@jduabe.dev"

[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "TIL"
  weight = 2
  url  = "til/"

[[menu.main]]
  name = "Blogroll"
  weight = 3
  url  = "blogroll/"

[[menu.main]]
  name = "Podroll"
  weight = 4
  url  = "podroll/"

[[menu.main]]
  name = "Colophon"
  weight = 5
  url  = "colophon/"

[[menu.main]]
  name = "Projects"
  weight = 6
  url  = "projects/"
